package io.openems.edge.meter.landis.dlms;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;

@ObjectClassDefinition(name = "Meter Landis DLMS", description = "A Landis meter that communicates via DLMS.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Meter-Type", description = "What is this meter used for?")
	MeterType type() default MeterType.GRID;

	@AttributeDefinition(name = "DLMS Bridge-ID", description = "ID of DLMS Bridge.")
	String dlms_id() default "bridgeDlmsSerial0";

	@AttributeDefinition(name = "DLMS Bridge target filter", description = "This is auto-generated by 'DLMS Bridge-ID'.")
	String dlms_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Meter Landis DLMS [{id}]";
}
